# Logging
logging:
  level:
    root: debug
    br:
      com:
        lkt: debug

# Feign
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
